DynamicProjectPage.create!([
	 {title: "Недвижимость в Алании", project_category_id: 1},
	 {title: "Алания центр", project_category_id: 2},
	 {title: "Авсалар", project_category_id: 6},
	 {title: "Конаклы", project_category_id: 11},
	 {title: "Оба", project_category_id: 10},
	 {title: "Тохмур", project_category_id: 15},
	 {title: "Кестель", project_category_id: 8},
	 {title: "Махмутлар", project_category_id: 9},
	 {title: "Каргыджак", project_category_id: 12},
	 {title: "Газипаша", project_category_id: 3},
	 {title: "Недвижимость в Анталии", project_category_id: 2},
	 {title: "Недвижимость в Сиде", project_category_id: 14},
	 {title: "Недвижимость в Кемере", project_category_id: 7},
	 {title: "Недвижимость в Бордуме", project_category_id: 4},
	 {title: "Недвижимость в Белеке", project_category_id: 5},
	 {title: "Недвижимость в Каш", project_category_id: 13},
])
